### ISSUE TITLE
Release planning for v1.086

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#529]
I have a few updates/upgrades I’m hoping to include in a new release, which will be v1.086. This issue is a simple place to plan and track them.

- [ ] Fix main kink issues in https://github.com/arrowtype/recursive/issues/527
- [ ] Include split roman/italic VFs (https://github.com/arrowtype/recursive/issues/526)
- [ ] Update "code" fonts
- [ ] Maybe include a proportional "code" font
- [ ] Merge https://github.com/arrowtype/recursive/issues/524
- [ ] Check and close https://github.com/arrowtype/recursive/issues/515

I may add more, but those are the task at the top of mind right now.

**Comment by arrowtype** [comment]
Working on this in https://github.com/arrowtype/recursive/pull/531
